const errorCodes = {
  ALREADY_WORKSPACE_MEMBER: "ALREADY_WORKSPACE_MEMBER",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  CHANNEL_ALREADY_EXISTS: "CHANNEL_ALREADY_EXISTS",
};

export default errorCodes;
